### PR TITLE
Process jira marker during tests collecting

### PR DESCRIPTION
**Pull request by gdyuldin**
Processing jira markers during tests collecting has next pros:

* xUnit report contains `xpassed` reason (link to the jira ticket) in
case of `xfail_strict` is enabled.
* Invalid marks format blocks tests execution immediately.
* Jira availability not impact tests execution after collecting.
* Allure-python plugin treated xfailed results as error without `xfail`
pytest mark.

### CODE REVIEW

**Comment by lukas-bednar** [comment]
Fixes #68 .
@liiight Could you please take a look as well since you reported the issue above?

**Comment by liiight** [comment]
So this moves plugin logic from test execution to test collection? Makes sense to me. Pros look great.

**Comment by gdyuldin** [comment]
Yes, it moves logic to collecting.

With next tests
```python
import pytest

@pytest.mark.jira('CND-8629')
def test_pass():
    assert True

@pytest.mark.jira('CND-8629')
def test_fail():
    assert False

@pytest.mark.jira('CND-8629', run=False)
def test_pass_norun():
    assert True

@pytest.mark.jira('CND-8629', run=False)
def test_fail_norun():
    assert False
```
With enabled [xfail_strict](https://docs.pytest.org/en/latest/skipping.html#strict-parameter) it generates next report
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="1" name="pytest" skips="3" tests="4" time="0.581">
    <testcase classname="test_foo" file="test_foo.py" line="4" name="test_pass" time="0.002123117446899414">
        <failure message="[XPASS(strict)] https://jira/browse/CND-8629">[XPASS(strict)] https://jira/browse/CND-8629</failure>
    </testcase>
    <testcase classname="test_foo" file="test_foo.py" line="9" name="test_fail" time="0.0051174163818359375">    <skipped message="expected test failure">https://jira/browse/CND-8629</skipped>
    </testcase>
    <testcase classname="test_foo" file="test_foo.py" line="14" name="test_pass_norun" time="0.00080108642578125">
        <skipped message="https://jira/browse/CND-8629" type="pytest.skip">test_foo.py:14: &lt;py._xmlgen.raw object at 0x7f8368445c18&gt;</skipped>
    </testcase>
    <testcase classname="test_foo" file="test_foo.py" line="19" name="test_fail_norun" time="0.0010704994201660156">
        <skipped message="https://jira/browse/CND-8629" type="pytest.skip">test_foo.py:19: &lt;py._xmlgen.raw object at 0x7f8368445d30&gt;</skipped>
    </testcase>
</testsuite>
```

**Comment by lukas-bednar** [comment]
Thank you!

**Pull request merged**
