### PR TITLE
Report invalid parameter of decorator

### PR DESCRIPTION
**Pull request by vkondula**
Exception is raised if the parametr of jira marker decorator
does not match the pattern.

### CODE REVIEW

**Comment by lukas-bednar** [comment]
fix #25

**Comment by lukas-bednar** [comment]
I am curious why Travis wasn't triggered ...

**Comment by vkondula** [comment]
> I am curious why Travis wasn't triggered ...
Not a clue. I've rebased it and pushed again and now it was triggered..

**Comment by lukas-bednar** [comment]
:+1:

**Pull request merged**
